### PR TITLE
fixed working xterm (256 colors)

### PR DESCRIPTION
**Pull request by avelino**
Convert values between RGB hex codes (approximation) and xterm-256 color codes
used https://gist.github.com/MicahElliott/719710

#20
#16
#21
#23

> If you're fixing a UI issue, make sure you take two screenshots. One that shows the actual bug and another that shows how you fixed it.

screenshot 2017-05-08 11 43 54
screenshot 2017-05-08 11 44 28

### CODE REVIEW

**Comment by film42** [comment]
This is really cool! Thanks!

@benjamreynolds @eigengrau what do you think?

**Comment by benreyn** [comment]
Looks like a solid implementation, and follows most of the same conventions as spacemacs-theme. (Which leads me to believe it will work pretty well)

Id be interested to find out if this works in both environments accurately with emacs running in daemon mode and connecting to it with a gui client, and also with a terminal client.

@avelino Im not in a position to pull the down and test myself right now. Can you test this and post screenshots of the results?

**Comment by eigengrau** [comment]
`if-display-graphic-p` won’t work when running as daemon. This was briefly discussed in #20. When running Emacs in daemon mode, it would evaluate once, namely while the daemon is starting up, and it would evaluate to `nil`, iirc. Instead, `custom-theme-faces` can do the switching of values based on the display type, cf. how this is done for the `default` face currently.

**Comment by eigengrau** [comment]
E.g., this will set a blue background on the terminal, but a white one in Xorg.

```
(custom-set-faces '(default
                       ((((type nil)) (:background "blue"))
                        (((type x)) (:background "white")))))
```

Only that we probably don’t want `type x`, since this won’t work everywhere. I think this would work more generally:

```
(custom-set-faces '(default
                       ((((type nil)) (:background "blue"))
                        (((class color)) (:background "white")))))

```

The face spec syntax is listed in the `defface` documentation.

**Comment by benreyn** [comment]
Thanks for clearing this up @eigengrau, I seemed to remember this from your previous PR, but didnt recall the details.

**Comment by benreyn** [comment]
@avelino are you up for refactoring this to use the approach @eigengrau described? If not I can take over this one. I would hate to see the work you did nailing down all the correct variations of these colors go to waste.

**Comment by film42** [comment]
@benjamreynolds thanks for being willing to help out :) Looks like you can take over this PR.

**Comment by avelino** [comment]
@benjamreynolds sorry delay to reply.
I'm out of time to get back in that PR.
You can continue, please.

**Comment by benreyn** [comment]
So, Ive been thinking about this one and playing around with some things. On the whole I dont think this is bad to merge in as is. The "emacs running as a daemon and connecting with term / gui" is problem with almost all themes. This PR should not affect existing functionality, and things should look fine running as daemon. 

The problem with the solution suggested by @eigengrau is that we need to tell each face definition what color to use on term and gui.

@film42 I think this (or #29 if you want to reopen that one, I can clean it up for merging, but its a bit more robust that this one) should be fine to merge.

**Comment by eigengrau** [comment]
> The "emacs running as a daemon and connecting with term / gui" is problem with almost all themes. 

Not universally so, since themes normally don’t use `if-display-graphic-p`. The problem is that this will evaluate to `nil` for anyone running Emacs as a daemon (and that’s quite a few) and will break colors for them in case they ever use Xorg windows.

> The problem with the solution suggested by @eigengrau is that we need to tell each face definition what color to use on term and gui.

It wouldn’t really be much different in spirit from the existing PR. You just need to do the switching using the native theme system. It’s designed to handle exactly this issue. If you are concerned about DRY, you can use macros.

**Comment by avelino** [comment]
#29 better than #26

**Pull request closed without merging**
