### PR TITLE
Cercueil

### PR DESCRIPTION
**Pull request by Nollo**
This is my first contribution to this fantastic theme. I use Spacemacs and I did few customizations that fit my tastes, but I think it could be a global improvement.

3 majors updates:
- Sorting & grouping faces
- Change color for builtin, const, type
- customization for org, web, diff-hl

I also added the red color (from dracula color sheet).
# Clojure

Minor changes, but now you can see namespaces better

**Clojure before...**
Clojure Before
**Clojure after!**
Clojure After
# Org

Some works for a better adaption of the theme to orgmode. I added some extra things like bigger headline or strike line for DONE.

**Org before...**
org-before
**Org after!**
org-after
# HTML

Few tweaks for web mode, I find it more dracula-esque.

**HTML before...**
html-before
**HTML after!**
html-after
# JS

Well, I didn't change specific things, but there are side effects, and it's still nice

**JS before...**
js-before
**JS after!**
js-after

### CODE REVIEW

**Comment by film42** [comment]
I like the changes, personally. I'm going to leave this open to a vote. Use 👍 / 👎 reactions to vote.

**Comment by iensu** [comment]
So will this be merged? :)

**Comment by film42** [comment]
Let's do it!

**Comment by film42** [comment]
Thanks @Nollo for your contribution, and thanks to all the people who voted!

**Pull request merged**
