### PR TITLE
Neo-tree colors, fixes #42

### LINKED ISSUE #42: neotree file color should be brighter
image

The color for neotree files name are too close to the background, which is hard to identify them

### PR DESCRIPTION
**Pull request by razum2um**
Original screenshot: https://github.com/dracula/emacs/issues/42
Screenshot after (in 256 terminal mode):
Screenshot 2020-05-12 at 08 29 35

### CODE REVIEW

**Review by milouse — COMMENTED** [review]
Hi! Thank you very much for your contribution.

Is there a reason you add only these three faces? Neo-tree as [a lot of other hard-coded faces](https://github.com/jaypei/emacs-neotree/blob/dev/neotree.el#L408). Do you plan to add them in a near future or you don't use them and prefer to let someone else do it?

**Comment by razum2um** [comment]
There's a lot of `neo-vc` faces and I'm unsure are they applied, not using `vc`.
I also tried various `neo-theme`s but didn't notice where the rest banner/button/header are applied as well ¯\_(ツ)_/¯ 

Generally, imo it's enough to customize just those 3 to get usable look again

**Comment by milouse** [comment]
Ok. Can you provide a screenshot of the result of your changes from a graphical emacs session for memory purpose? Thank you very much.

**Comment by milouse** [comment]
I add the missing color and align `neo-file-link-face` on the speedbar color for files (besides, `,fg1` doesn't exists). Thank you very much for your contribution.

Merged as c162aff5025a7e9f55785d7177d59f4a3aa60183

**Pull request closed without merging**
