### PR TITLE
Fixing the blue background on iTerm2 with macOS

### PR DESCRIPTION
**Pull request by florianmari**
> If you're fixing a UI issue, make sure you take two screenshots. One that shows the actual bug and another that shows how you fixed it.

### CODE REVIEW

**Comment by film42** [comment]
Hey! Thanks for the PR. Would you mind adding some screenshots?

**Comment by florianmari** [comment]
Of course, before the PR

capture d ecran 2016-12-05 a 18 00 17

Now: 

capture d ecran 2016-12-05 a 17 58 46

It is based on an issue already opened

**Comment by film42** [comment]
Thank you! This might be a better stop-gap solution than waiting for official 24-bit color support. I'm 👍 for it, but let's feel it out for a few days and let people vote on it. Voting seems to have worked pretty good so far.

**Comment by film42** [comment]
Or.. should we use @apierz 's proposed color? https://github.com/dracula/emacs/issues/2#issuecomment-227934433 (It looks good with some transparency, but I would like to see it without a transparent background).

**Comment by florianmari** [comment]
My screenshots are without transparency

**Comment by film42** [comment]
@florianmari I was referring to @apierz 's screenshot in the issue. Yours look 😍 ! 😄

**Comment by benreyn** [comment]
I think I personally prefer the color @apierz's color. I too would like to see it without the transparency.

PS, Hi new Dracula user here, converted from Tomorrow Eighties, excited to be a part of the community here.

**Comment by benreyn** [comment]
Friendly ping @apierz, could we get an better screenshot of your change, and maybe a PR for it?

**Comment by apierz** [comment]
Here is a screenshot. I'll put together a pull request in a minute.

screen shot 2017-02-23 at 3 44 26 pm

**Comment by apierz** [comment]
OK I added a pull request, it's #18 .

**Pull request closed without merging**
