### PR TITLE
Fix colortheme to work in both terminal and GUI emacs

### PR DESCRIPTION
**Pull request by benreyn**
The approach used mimics the approach from [spacemacs-theme]

[spacemacs-theme]: https://github.com/nashamri/spacemacs-theme

This PR replaces PR #26

### CODE REVIEW

**Comment by benreyn** [comment]
Screenshots... 

Emacs started as daemon, connected to daemon in terminal...
screenshot_7_3_17__10_10_am
And connected to the same daemon in a GUI
screenshot_7_3_17__10_12_am

**Comment by benreyn** [comment]
Closing this.... realizing now that this approach is flawed. (Also, pretty sure than any approach to this issue might be flawed.)

**Comment by benreyn** [comment]
I will do some more playing around with this when I get more free time. There has got to be a decent solution.

**Comment by film42** [comment]
@benjamreynolds thanks for taking a cut at this! Looking forward to seeing what you come up with!

**Pull request closed without merging**
