### PR TITLE
[DOCS] Update Homebrew Formulae to be correct

### PR DESCRIPTION
**Pull request by mattclegg**
Does this appear to be a typo?

### CODE REVIEW

**Comment by milouse** [comment]
I honnestly have no idea of what is this thing. I don't use a Mac, thus I've no idea what is the correct line. Obviously the `helm` reference here is a typo, but even after I did a quick search to try to find what are these `dunn/emacs/helm` or `dunn/emacs/dracula-emacs`, I found nothing (no related github repositories or official homebrew package).

I would like you to show me the proof than `dunn/emacs/dracula-emacs` is the right thing to have here (link to the related formulae for example). If you cannot, I'll simply remove this lines as deprecated/wrong instructions.

Thank you very much for your help.

**Comment by mattclegg** [comment]
This is the info about the repository from brew;

```
$ brew info dunn/emacs/dracula-emacs
dunn/emacs/dracula-emacs: stable 1.2.5, HEAD
Dark color theme available for a number of editors.
https://github.com/dracula/emacs
/usr/local/Cellar/dracula-emacs/1.2.5 (3 files, 18KB) *
  Built from source on 2020-04-02 at 13:16:17
From: https://github.com/dunn/homebrew-emacs/blob/master/Formula/dracula-emacs.rb
==> Requirements
Required: emacs ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/dracula-emacs
```

It looks right as it's installing from here; [brew formula](https://github.com/brew-stuff/homebrew-emacs/blob/master/Formula/dracula-emacs.rb), although it's a bit out of date.

**Comment by milouse** [comment]
Mmmh, I see a lot of deprecation warnings, MR seem abandoned since september at least and no activity since 1 year. Feel free to open an MR on their side to upgrade the recipe to the new dracula version (they only provide the 1.2.5, which is 4 years old!), but on our side, to avoid bad suprises, I'll remove this information.

**Comment by mattclegg** [comment]
Yeah it looks like the repo might have been deprecated but let us see; https://github.com/brew-stuff/homebrew-emacs/pull/759 🤞

**Pull request closed without merging**
