### PR TITLE
Add selectrum-mode dracula colors

### PR DESCRIPTION
**Pull request by kekeimiku**
IMG_20201028_001014_894

### CODE REVIEW

**Review by milouse — CHANGES_REQUESTED** [review]
Hi, and thank you very much for your work!

If you don’t mind, could you just move your three new color settings in the right place in the file? Modes are alphabetically sorted to help one find them back quickier.

Thanks again!

**Comment by kekeimiku** [comment]
> 嗨，非常感谢您的工作！
> 
> 如果您不介意，能否将三个新的颜色设置移动到文件中的正确位置？模式按字母顺序排序，以帮助人们更快地找到它们。
> 
> 再次感谢！

**Comment by kekeimiku** [comment]
> Hi, and thank you very much for your work!
> 
> If you don’t mind, could you just move your three new color settings in the right place in the file? Modes are alphabetically sorted to help one find them back quickier.
> 
> Thanks again!

Sorry, I did not notice your reply. Now modified

**Comment by kekeimiku** [comment]
I accidentally closed the PR. . Now at https://github.com/dracula/emacs/pull/74 ......

**Pull request closed without merging**
