### PR TITLE
Add faces for rpm-spec-mode

### PR DESCRIPTION
**Pull request by ghost**
> If you're fixing a UI issue, make sure you take two screenshots. One that shows the actual bug and another that shows how you fixed it.

### CODE REVIEW

**Comment by film42** [comment]
Could you please attach some screenshots? :)

**Comment by ghost** [comment]
Before:

dracula-rpm-spec-mode-before

After:

dracula-rpm-spec-mode-after

**Comment by film42** [comment]
Looks great!

**Comment by film42** [comment]
Thank you, @fszymanski !!

**Comment by film42** [comment]
Released as `1.2.6`.

**Pull request merged**
